### ISSUE TITLE
Wuhu Station Set Initial Release: Tracking Issue

### ISSUE THREAD

**Issue by ahyangyi** [ahyangyi/openttd-newgrfs#13]
# Blocking issues
* [x] Switch name to a China Set Addon (#17)
* [x] Shed graphics (#14)
* [x] Pillar graphics (#12 
* [x] Entrance graphics (#12)
* [x] 4 Fully functional flexible stations (#15, #16)
* [x] Set version correctly (a236c60104de7ee8e42ab0246bc19c0736a70acd)

# Nice-to-haves
* [x] Switch from "white" to "modern" platforms (#12)
* [x] Window details (#12)
* [x] Remove redundant (internal) 1cc decorations, replace them with windows (#12)
* [ ] Big red letter graphics
* [ ] Escalator graphics
* [ ] Elevated station buildings

# Non-goals
* Night graphics
* Smart platform switcher
* Any mode besides "flexible" and "modular"

# Preliminary release date
~~2024-04-21~~ 2024-04-30
