### ISSUE TITLE
September Release Tracking Issue

### ISSUE THREAD

**Issue by ahyangyi** [ahyangyi/openttd-newgrfs#48]
# Features
* [x] A stable id assignment scheme (#54)
* [x] Parameters to reduce UI clutter (#51)
* [x] Backwards compatibility mode (#42, #64)
* Graphics Update
    * [x] Detailing platform-facing sides of station building (#46)
    * [x] Snow tweaking: reduce the amount of snow on the big window (#46)

# Nice-to-haves
* ~~[ ] Snow parameter (#32)~~: Deemed impossible in current version, will file a feature request / bug report
* [x] Waypoint classes (#49)
* [x] Decorative objects (#41, #61)
* [x] Smaller purchase sprites (#52, #59, #60)
* Graphics Update
    * ~~[ ] Underground staircases~~: Future work

**Comment by ahyangyi** [comment]
Released as 989c043373d00d95de486516f14eb969e3659383 (version 0.3.0)
